//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cal_Pomona_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int FK_Role_Id { get; set; }
        public int User_Id { get; set; }
        public string Password { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
